language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
  - npm install -g typescript@~3.4.5
script:
- bash index.sh
deploy:
  provider: heroku
  api_key:
    secure: 932923e3-ea19-4f25-8cab-3ec0ff04dea6
