language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
script:
- npm start

env:
 - JWT_KEY="l0calho$t"
 - DB_URI="mongodb://bookshelf-dev:bookshelf-dev-password5000@ds046027.mlab.com:46027/bookshelf5000"
 - SESSION_KEY="e7e42$f%b433g7hc2a4535"

deploy:
  provider: heroku
  api_key:
    secure: 932923e3-ea19-4f25-8cab-3ec0ff04dea6
